### ISSUE TITLE
Setup the Kanban Board

### ISSUE THREAD

**Issue by Mofuhidy** [clin2on3mun/Recipe-app#10]
Our [Kanban board](https://github.com/users/clin2on3mun/projects/3)

We are group of two students
@Mofuhidy & @clin2on3mun

**Comment by Olamarx** [comment]
Hi Team,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Fair distribution of tasks ✔️
- Good use of Kanban board ✔️

## Required Changes ♻️
_Check the comments under the review._
- [x] I will encourage you to see the N+1 as serious as other tasks because at the moment, it does not reflect in your project tasks. These N+1 queries can lead to a lot of unnecessary database hits, causing performance issues so I will encourage you to add it and remember to work on it in your project.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @Mofuhidy and @clin2on3mun,

## Highlights!
- Descriptive issue ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
